CREATE TABLE athlete_record (
    id uuid DEFAULT gen_random_uuid(),
    athlete_id uuid REFERENCES athlete_data,
    snatch int DEFAULT 0,
    clean_and_jerk int DEFAULT 0,
    jerk int DEFAULT 0,
    clean int DEFAULT 0,
    back_squat int DEFAULT 0,
    front_squat int DEFAULT 0,
    deadlift int DEFAULT 0,
    snatch_deadlift int DEFAULT 0,
    push_press int DEFAULT 0,
    strict_press int DEFAULT 0,
    bent_over_row int DEFAULT 0,
    power_snatch int DEFAULT 0,
    power_clean int DEFAULT 0,
    power_jerk int DEFAULT 0,
    hang_snatch int DEFAULT 0,
    hang_clean int DEFAULT 0,
    hang_power_snatch int DEFAULT 0,
    hang_power_clean int DEFAULT 0,
    block_snatch int DEFAULT 0,
    block_clean int DEFAULT 0,
    block_power_snatch int DEFAULT 0,
    block_power_clean int DEFAULT 0,
    clean_pull int DEFAULT 0,
    snatch_pull int DEFAULT 0,
    snatch_high_pull int DEFAULT 0,
    bench_press int DEFAULT 0,
    pendlay_row int DEFAULT 0,
    snatch_push_press int DEFAULT 0,
    overhead_squat int DEFAULT 0,
    squat_jerk int DEFAULT 0,
    max_pull_ups int DEFAULT 0,
    weighted_pull_up int DEFAULT 0,
    max_chin_ups int DEFAULT 0,
    weighted_chin_up int DEFAULT 0,
    pause_snatch int DEFAULT 0,
    pause_clean int DEFAULT 0,
    sandbag_carry_meters int DEFAULT 0,
    sandbag_carry_weight int DEFAULT 0,
    farmer_carry_meters int DEFAULT 0,
    farmer_carry_weight int DEFAULT 0,

    PRIMARY KEY (id)
);

INSERT INTO athlete_record (athlete_id)
SELECT id
FROM athlete_data;